name: Sample-api Image Test Build and Push

on:
  push:
    branches:
      - main
      - feature/qa-02
  pull_request:

jobs:
  sample-api-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up QEMU for multi-platform builds
      uses: docker/setup-qemu-action@v3
      with:
        platforms: amd64,arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        push: true
        tags: sample-api:latest
        platforms: linux/amd64,linux/arm64
        
    - name: Run test
      run: |
        docker run --rm sample-api:latest bash -c ./run-unit-tests.sh
